name: ZT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  S1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true

      - name: Clone repo from secret
        run: |
          REPO="${{ secrets.XY }}"
          FOLDER=$(echo "$REPO" | md5sum | cut -d' ' -f1)
          git clone --depth=1 "$REPO" "$FOLDER" || { echo "Clone failed"; exit 1; }

      - name: Copy M3U files
        run: |
          TARGET="playlist"
          mkdir -p "$TARGET"
          if [ -d "$FOLDER/streams" ]; then
            find "$FOLDER/streams" -type f -name "*.m3u" -exec cp --parents {} "$TARGET"/ \;
          else
            echo "No streams folder found!"
          fi

      - name: Count files
        run: |
          echo "Count: $(find "$TARGET" -type f -name '*.m3u' | wc -l)"

      - name: Commit & push
        run: |
          git config user.name "AB"
          git config user.email "ab@x.com"
          if [ -d "$TARGET" ] && [ "$(ls -A $TARGET)" ]; then
            git add "$TARGET"
            git diff --cached --quiet || git commit -m "Update M3U files"
            git push origin main
          else
            echo "No files to commit."
          fi
