name: ZT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  S1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repo from secret
        run: |
          REPO="${{ secrets.XY }}"
          FOLDER=$(echo "$REPO" | md5sum | cut -d' ' -f1)
          git clone --depth=1 "$REPO" "$FOLDER"

      - name: files
        run: |
          TARGET=$(echo "${{ secrets.XYC }}" | sha1sum | cut -d' ' -f1)
          mkdir -p "$TARGET"
          # Copy all .m3u files recursively preserving folder structure
          find "$FOLDER"/streams/ -type f -name "*.m3u" -exec cp --parents {} "$TARGET"/ \;

      - name: Count files
        run: |
          echo "Count: $(find "$TARGET" -type f -name '*.m3u' | wc -l)"

      - name: Commit & push
        run: |
          git config user.name "AB"
          git config user.email "ab@x.com"
          git checkout main
          git add "$TARGET"
          git diff --cached --quiet || git commit -m "Update M3U files"
          git push origin main
