name: Update Token Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate random token, Base64 encode and update JSON
      run: |
        TOKEN=$(uuidgen)
        TOKEN_BASE64=$(echo -n "$TOKEN" | base64)
        echo "{\"token\": \"$TOKEN_BASE64\"}" > token.json

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add token.json
        git commit -m "Update token [skip ci]" || echo "Nothing to commit"
        git push
